Тестовый вариант поиска фильмов + стили для main-section
heorhii-aksiuk/team-proj-js pull request #29
Opened 2021-11-09 17:16 UTC by DenysMelnychenko2021

2021-11-09 17:39 UTC, heorhii-aksiuk commented on src/js/dom/show-searched-films.js
> +const collectionList = document.querySelector('.collection__list');
для рефов у нас отдельный файл refs.js

2021-11-09 17:46 UTC, DenysMelnychenko2021 commented on src/js/dom/show-searched-films.js
> +const collectionList = document.querySelector('.collection__list');
ок, думал при рефакторинге сделать

2021-11-09 19:21 UTC, DenysMelnychenko2021 commented on src/js/dom/show-searched-films.js
> +const collectionList = document.querySelector('.collection__list');
Исправил

2021-11-09 22:16 UTC, heorhii-aksiuk requested changes
Встраивай разметку через innerHTML, а не через insertAdjacentHTML. Иначе в конце  остаются карточки которые изначально на странице, а они должны убираться

2021-11-09 22:16 UTC, heorhii-aksiuk commented on src/js/dom/show-searched-films.js
> +  search.then(arr => collectionList.insertAdjacentHTML('afterbegin', filmCard(arr)));
нужно не встраивать в разметку, а заменять, то есть нужно InerHTML, иначе у нас остаются предыдущие фильмы в конце списка

2021-11-09 22:22 UTC, heorhii-aksiuk commented
и почисти консоли, или хотя бы закомментируй, они будут мешать другим работать над своей частью

2021-11-09 22:23 UTC, heorhii-aksiuk commented
На конфликт не обращай внимания

2021-11-10 12:56 UTC, DenysMelnychenko2021 commented on src/js/dom/show-searched-films.js
> +  search.then(arr => collectionList.insertAdjacentHTML('afterbegin', filmCard(arr)));
ок, спасибо!

2021-11-10 16:04 UTC, heorhii-aksiuk commented
Решил конфликт

2021-11-10 16:08 UTC, heorhii-aksiuk approved these changes

2021-11-10 16:08 UTC, merged