home-switch-render
heorhii-aksiuk/team-proj-js pull request #34
Opened 2021-11-10 08:19 UTC by koljuchka93

add refreshPage to home btn and logo

2021-11-10 12:14 UTC, heorhii-aksiuk commented
Был конфликт

2021-11-10 12:16 UTC, heorhii-aksiuk requested changes

2021-11-10 12:16 UTC, heorhii-aksiuk commented on src/partials/header.html
> +            <button class="menu__button home-button" type="button" onClick="refreshPage()">Home</button></a>
Что делает JS в HTML? Нас не так учили. Создаём рефы и слушаем кнопку в JS файлах

2021-11-10 15:44 UTC, koljuchka93 commented on src/partials/header.html
> +            <button class="menu__button home-button" type="button" onClick="refreshPage()">Home</button></a>
Удалила лишнее.

2021-11-10 19:34 UTC, tuzegor commented
Катя, обнови мейн. Там есть файл home-library-page-switch.js
там есть слушатели событий хоум и лайбрари, впиши туда свою функцию рендора для хоум

2021-11-11 17:10 UTC, heorhii-aksiuk commented
![image](https://user-images.githubusercontent.com/81520242/141339855-d8ae55e4-12a4-4cd7-8128-014d08f44164.png)

2021-11-11 17:13 UTC, heorhii-aksiuk requested changes
Надо пофиксить, чтобы не было как на картинке что я скинул выше

2021-11-14 11:25 UTC, closed without merging